version: "1.1"
name: ""
stages:
  - stage:
      - git-checkout:
          alias: git-checkout
          description: 代码仓库克隆
          params:
            depth: 1
          resources:
            cpu: 0.3
            mem: 512
  - stage:
      - java:
          alias: gateway-service
          description: 针对 java 工程的编译打包任务，产出可运行镜像
          version: "1.0"
          params:
            build_cmd: mvn clean package  -Dmaven.test.skip=true
            build_type: maven
            container_type: spring-boot
            jdk_version: "11"
            service_name: gateway-service
            target: /.pipeline/container/context/git-checkout/target/gateway-service-0.0.1-SNAPSHOT.jar
            workdir: ${git-checkout}
          resources:
            cpu: 0.5
            mem: 1024
  - stage:
      - release:
          alias: release
          description: 用于打包完成时，向dicehub 提交完整可部署的dice.yml。用户若没在pipeline.yml里定义该action，CI会自动在pipeline.yml里插入该action
          version: "1.0"
          params:
            dice_yml: ${git-checkout}/dice.yml
            image:
              gateway-service: ${gateway-service:OUTPUT:image}
  - stage:
      - dice:
          alias: dice
          description: 用于 Erda 平台部署应用服务
          version: "1.0"
          params:
            release_id: ${release:OUTPUT:releaseID}
            time_out: 1800
