version: "1.1"
name: ""
"on":
  push:
    branches:
      - dev
      - feature/*
      - release/*
stages:
  - stage:
      - git-checkout:
          alias: git-checkout
          description: 代码仓库克隆
          version: "1.0"
          params:
            depth: 1
          timeout: 3600
  - stage:
      - sonar:
          alias: sonar
          description: 用于对代码仓库执行代码质量检测，生成质量检测报告
          version: "2.0"
          params:
            code_dir: ${{ dirs.git-checkout }}
            must_gate_status_ok: "true"
            sonar_host_url: http://sonarqube-5c70646cbc.project-4-staging.svc.cluster.local:9000
            sonar_login: e2ff393ea76bf2470502278f7def2ad35fa45830
            sonar_project_key: cep-common
          resources:
            cpu: 0.5
            mem: 1024
          disable: true
  - stage:
      - java-build:
          alias: java-build
          description: 针对 java 工程的编译打包任务
          version: "1.0"
          params:
            build_cmd:
              - gitBranch=((gittar.branch))  && mvn versions:set -DnewVersion="${gitBranch##*/}" && mvn clean deploy -U -s settings.xml -Dmaven.test.skip
            jdk_version: "11"
            workdir: ${git-checkout}
          resources:
            cpu: 0.5
            mem: 512
          caches:
            - path: /root/.m2/repository
