server:
  port: 9000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: data-reporting-service
          uri: lb://data-reporting-service
          predicates:
            - Path=/reporting/**
          filters:
            - StripPrefix=1
        - id: data-consumption-cleaning-service
          uri: lb://data-consumption-cleaning-service
          predicates:
            - Path=/consumption/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: nacos.addon-nacos--e0f94db56a3be411995e4cdffd5b38caa.svc.cluster.local:8848
      config:
        server-addr: nacos.addon-nacos--e0f94db56a3be411995e4cdffd5b38caa.svc.cluster.local:8848