server:
  port: 9000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: data-reporting-service
          uri: lb://data-reporting-service
          predicates:
            - Path=/reporting/**
          filters:
            - StripPrefix=1
        - id: data-consumption-cleaning-service
          uri: lb://data-consumption-cleaning-service
          predicates:
            - Path=/consumption/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
  config:
    import: nacos:gateway-service.yml